[package]
name = "gorillas"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
license = "EUPL-1.2"

[dependencies]
anyhow = "1"
bytemuck = { version = "1.15", features = ["derive"] }
cpal = "0.17"
pollster = "0.4.0"
rand = "0.10.1"
synthie = "0.4.0"
winit = "0.30.13"
wgpu = "29.0.1"
crossbeam-channel = "0.5.15"
